version: '2'
services:
    nginx:
        container_name: nginx_ct
        image: nginx
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/wwwroot:/var/wwwroot:ro
            - ./nginx/logs:/var/log/nginx
        environment:   
            - TZ=Asia/Shanghai
        ports:
            - "80:80"
        depends_on:
            - php
        links:
            - php
        restart: always


    php:
        container_name: php_ct
        image: php_img
        build:
            context: .
            dockerfile: ./php7.1-fpm/Dockerfile
        volumes:
            - ./nginx/wwwroot:/var/wwwroot
        environment:   
            - TZ=Asia/Shanghai
        restart: always
####已有php镜像
#    php:
#       container_name: php_ct
#       image: yxy_php
#       volumes:
#           - ./nginx/wwwroot:/var/wwwroot
#       restart: always
